package com.xiaosong.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("t_attendrule", "id", TAttendrule.class);
		arp.addMapping("t_auth", "id", TAuth.class);
		arp.addMapping("t_auth_range", "id", TAuthRange.class);
		arp.addMapping("t_company_auth", "id", TCompanyAuth.class);
		arp.addMapping("t_company_auth_range", "id", TCompanyAuthRange.class);
		arp.addMapping("t_company_menu", "id", TCompanyMenu.class);
		arp.addMapping("t_company_oper", "id", TCompanyOper.class);
		arp.addMapping("t_company_role", "id", TCompanyRole.class);
		arp.addMapping("t_dict", "id", TDict.class);
		arp.addMapping("t_dict_item", "id", TDictItem.class);
		arp.addMapping("t_error_log", "id", TErrorLog.class);
		arp.addMapping("t_menu", "id", TMenu.class);
		arp.addMapping("t_oper", "id", TOper.class);
		arp.addMapping("t_org", "id", TOrg.class);
		arp.addMapping("t_role", "id", TRole.class);
		arp.addMapping("t_system_param", "id", TSystemParam.class);
		arp.addMapping("t_visit_access_record", "id", TVisitAccessRecord.class);
		arp.addMapping("tbl_ad_banner", "id", TblAdBanner.class);
		arp.addMapping("tbl_app_version", "id", TblAppVersion.class);
		arp.addMapping("tbl_button", "id", TblButton.class);
		arp.addMapping("tbl_company", "id", TblCompany.class);
		arp.addMapping("tbl_company_button", "id", TblCompanyButton.class);
		arp.addMapping("tbl_company_post", "id", TblCompanyPost.class);
		arp.addMapping("tbl_company_section", "id", TblCompanySection.class);
		arp.addMapping("tbl_company_user", "id", TblCompanyUser.class);
		arp.addMapping("tbl_date_declare", "cla_date", TblDateDeclare.class);
		arp.addMapping("tbl_devices", "id", TblDevices.class);
		arp.addMapping("tbl_in_out", "id", TblInOut.class);
		arp.addMapping("tbl_key", "id", TblKey.class);
		arp.addMapping("tbl_news", "id", TblNews.class);
		arp.addMapping("tbl_notice", "id", TblNotice.class);
		arp.addMapping("tbl_org_vip_user", "id", TblOrgVipUser.class);
		arp.addMapping("tbl_params", "id", TblParams.class);
		arp.addMapping("tbl_posp", "id", TblPosp.class);
		arp.addMapping("tbl_room_apply_record", "id", TblRoomApplyRecord.class);
		arp.addMapping("tbl_share_room", "id", TblShareRoom.class);
		arp.addMapping("tbl_terminal", "id", TblTerminal.class);
		arp.addMapping("tbl_user", "id", TblUser.class);
		arp.addMapping("tbl_user_account", "id", TblUserAccount.class);
		arp.addMapping("tbl_user_friend", "id", TblUserFriend.class);
		arp.addMapping("tbl_user_message", "id", TblUserMessage.class);
		arp.addMapping("tbl_user_notice", "id", TblUserNotice.class);
		arp.addMapping("tbl_visitor_record", "id", TblVisitorRecord.class);
		arp.addMapping("tbl_visitor_record_maxid", "id", TblVisitorRecordMaxid.class);
	}
}

