package com.xiaosong.model;

import com.xiaosong.model.base.BaseTAttendrule;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TAttendrule extends BaseTAttendrule<TAttendrule> {
	public static final TAttendrule dao = new TAttendrule().dao();
}
