package com.xiaosong.model;

import com.xiaosong.model.base.BaseTAuth;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TAuth extends BaseTAuth<TAuth> {
	public static final TAuth dao = new TAuth().dao();
}
