package com.xiaosong.model;

import com.xiaosong.model.base.BaseTAuthRange;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TAuthRange extends BaseTAuthRange<TAuthRange> {
	public static final TAuthRange dao = new TAuthRange().dao();
}
