package com.xiaosong.model;

import com.xiaosong.model.base.BaseTblAppVersion;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TblAppVersion extends BaseTblAppVersion<TblAppVersion> {
	public static final TblAppVersion dao = new TblAppVersion().dao();
}
