package com.xiaosong.model;

import com.xiaosong.model.base.BaseTblAdBanner;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TblAdBanner extends BaseTblAdBanner<TblAdBanner> {
	public static final TblAdBanner dao = new TblAdBanner().dao();
}
