package com.xiaosong.model;

import com.xiaosong.model.base.BaseTblButton;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TblButton extends BaseTblButton<TblButton> {
	public static final TblButton dao = new TblButton().dao();
}
