package com.xiaosong.model;

import com.xiaosong.model.base.BaseTblCompanyUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TblCompanyUser extends BaseTblCompanyUser<TblCompanyUser> {
	public static final TblCompanyUser dao = new TblCompanyUser().dao();
}
