package com.xiaosong.model;

import com.xiaosong.model.base.BaseTblCompanyPost;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TblCompanyPost extends BaseTblCompanyPost<TblCompanyPost> {
	public static final TblCompanyPost dao = new TblCompanyPost().dao();
}
