package com.xiaosong.model;

import com.xiaosong.model.base.BaseTblCompanyButton;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TblCompanyButton extends BaseTblCompanyButton<TblCompanyButton> {
	public static final TblCompanyButton dao = new TblCompanyButton().dao();
}
