package com.xiaosong.model;

import com.xiaosong.model.base.BaseTblCompany;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TblCompany extends BaseTblCompany<TblCompany> {
	public static final TblCompany dao = new TblCompany().dao();
}
