package com.xiaosong.model;

import com.xiaosong.model.base.BaseTblCompanySection;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TblCompanySection extends BaseTblCompanySection<TblCompanySection> {
	public static final TblCompanySection dao = new TblCompanySection().dao();
}
