package com.xiaosong.model;

import com.xiaosong.model.base.BaseTblDevices;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TblDevices extends BaseTblDevices<TblDevices> {
	public static final TblDevices dao = new TblDevices().dao();
}
