package com.xiaosong.model;

import com.xiaosong.model.base.BaseTblDateDeclare;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TblDateDeclare extends BaseTblDateDeclare<TblDateDeclare> {
	public static final TblDateDeclare dao = new TblDateDeclare().dao();
}
