package com.xiaosong.model;

import com.xiaosong.model.base.BaseTblInOut;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TblInOut extends BaseTblInOut<TblInOut> {
	public static final TblInOut dao = new TblInOut().dao();
}
