package com.xiaosong.model;

import com.xiaosong.model.base.BaseTblKey;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TblKey extends BaseTblKey<TblKey> {
	public static final TblKey dao = new TblKey().dao();
}
