package com.xiaosong.model;

import com.xiaosong.model.base.BaseTblNews;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TblNews extends BaseTblNews<TblNews> {
	public static final TblNews dao = new TblNews().dao();
}
