package com.xiaosong.model;

import com.xiaosong.model.base.BaseTblNotice;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TblNotice extends BaseTblNotice<TblNotice> {
	public static final TblNotice dao = new TblNotice().dao();
}
