package com.xiaosong.model;

import com.xiaosong.model.base.BaseTblOrgVipUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TblOrgVipUser extends BaseTblOrgVipUser<TblOrgVipUser> {
	public static final TblOrgVipUser dao = new TblOrgVipUser().dao();
}
