package com.xiaosong.model;

import com.xiaosong.model.base.BaseTblParams;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TblParams extends BaseTblParams<TblParams> {
	public static final TblParams dao = new TblParams().dao();
}
