package com.xiaosong.model;

import com.xiaosong.model.base.BaseTblRoomApplyRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TblRoomApplyRecord extends BaseTblRoomApplyRecord<TblRoomApplyRecord> {
	public static final TblRoomApplyRecord dao = new TblRoomApplyRecord().dao();
}
