package com.xiaosong.model;

import com.xiaosong.model.base.BaseTblShareRoom;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TblShareRoom extends BaseTblShareRoom<TblShareRoom> {
	public static final TblShareRoom dao = new TblShareRoom().dao();
}
