package com.xiaosong.model;

import com.xiaosong.model.base.BaseTblTerminal;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TblTerminal extends BaseTblTerminal<TblTerminal> {
	public static final TblTerminal dao = new TblTerminal().dao();
}
