package com.xiaosong.model;

import com.xiaosong.model.base.BaseTblUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TblUser extends BaseTblUser<TblUser> {
	public static final TblUser dao = new TblUser().dao();
}
