package com.xiaosong.model;

import com.xiaosong.model.base.BaseTblUserNotice;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TblUserNotice extends BaseTblUserNotice<TblUserNotice> {
	public static final TblUserNotice dao = new TblUserNotice().dao();
}
