package com.xiaosong.model;

import com.xiaosong.model.base.BaseTblUserAccount;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TblUserAccount extends BaseTblUserAccount<TblUserAccount> {
	public static final TblUserAccount dao = new TblUserAccount().dao();
}
