package com.xiaosong.model;

import com.xiaosong.model.base.BaseTblUserFriend;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TblUserFriend extends BaseTblUserFriend<TblUserFriend> {
	public static final TblUserFriend dao = new TblUserFriend().dao();
}
