package com.xiaosong.model;

import com.xiaosong.model.base.BaseTblUserMessage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TblUserMessage extends BaseTblUserMessage<TblUserMessage> {
	public static final TblUserMessage dao = new TblUserMessage().dao();
}
