package com.xiaosong.model;

import com.xiaosong.model.base.BaseTblVisitorRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TblVisitorRecord extends BaseTblVisitorRecord<TblVisitorRecord> {
	public static final TblVisitorRecord dao = new TblVisitorRecord().dao();
}
