package com.xiaosong.model;

import com.xiaosong.model.base.BaseTblVisitorRecordMaxid;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TblVisitorRecordMaxid extends BaseTblVisitorRecordMaxid<TblVisitorRecordMaxid> {
	public static final TblVisitorRecordMaxid dao = new TblVisitorRecordMaxid().dao();
}
