package com.xiaosong.model;

import com.xiaosong.model.base.BaseTCompanyAuth;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TCompanyAuth extends BaseTCompanyAuth<TCompanyAuth> {
	public static final TCompanyAuth dao = new TCompanyAuth().dao();
}
