package com.xiaosong.model;

import com.xiaosong.model.base.BaseTCompanyOper;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TCompanyOper extends BaseTCompanyOper<TCompanyOper> {
	public static final TCompanyOper dao = new TCompanyOper().dao();
}
