package com.xiaosong.model;

import com.xiaosong.model.base.BaseTCompanyAuthRange;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TCompanyAuthRange extends BaseTCompanyAuthRange<TCompanyAuthRange> {
	public static final TCompanyAuthRange dao = new TCompanyAuthRange().dao();
}
