package com.xiaosong.model;

import com.xiaosong.model.base.BaseTCompanyRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TCompanyRole extends BaseTCompanyRole<TCompanyRole> {
	public static final TCompanyRole dao = new TCompanyRole().dao();
}
