package com.xiaosong.model;

import com.xiaosong.model.base.BaseTCompanyMenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TCompanyMenu extends BaseTCompanyMenu<TCompanyMenu> {
	public static final TCompanyMenu dao = new TCompanyMenu().dao();
}
