package com.xiaosong.model;

import com.xiaosong.model.base.BaseTDict;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TDict extends BaseTDict<TDict> {
	public static final TDict dao = new TDict().dao();
}
