package com.xiaosong.model;

import com.xiaosong.model.base.BaseTDictItem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TDictItem extends BaseTDictItem<TDictItem> {
	public static final TDictItem dao = new TDictItem().dao();
}
