package com.xiaosong.model;

import com.xiaosong.model.base.BaseTErrorLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TErrorLog extends BaseTErrorLog<TErrorLog> {
	public static final TErrorLog dao = new TErrorLog().dao();
}
