package com.xiaosong.model;

import com.xiaosong.model.base.BaseTMenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TMenu extends BaseTMenu<TMenu> {
	public static final TMenu dao = new TMenu().dao();
}
