package com.xiaosong.model;

import com.xiaosong.model.base.BaseTOper;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TOper extends BaseTOper<TOper> {
	public static final TOper dao = new TOper().dao();
}
