package com.xiaosong.model;

import com.xiaosong.model.base.BaseTOrg;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TOrg extends BaseTOrg<TOrg> {
	public static final TOrg dao = new TOrg().dao();
}
