package com.xiaosong.model;

import com.xiaosong.model.base.BaseTRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TRole extends BaseTRole<TRole> {
	public static final TRole dao = new TRole().dao();
}
