package com.xiaosong.model;

import com.xiaosong.model.base.BaseTSystemParam;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TSystemParam extends BaseTSystemParam<TSystemParam> {
	public static final TSystemParam dao = new TSystemParam().dao();
}
