package com.xiaosong.model;

import com.xiaosong.model.base.BaseTVisitAccessRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TVisitAccessRecord extends BaseTVisitAccessRecord<TVisitAccessRecord> {
	public static final TVisitAccessRecord dao = new TVisitAccessRecord().dao();
}
