package com.xiaosong.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTCompanyMenu<M extends BaseTCompanyMenu<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setMenuCode(java.lang.String menuCode) {
		set("menu_code", menuCode);
		return (M)this;
	}
	
	public java.lang.String getMenuCode() {
		return getStr("menu_code");
	}

	public M setMenuName(java.lang.String menuName) {
		set("menu_name", menuName);
		return (M)this;
	}
	
	public java.lang.String getMenuName() {
		return getStr("menu_name");
	}

	public M setMenuUrl(java.lang.String menuUrl) {
		set("menu_url", menuUrl);
		return (M)this;
	}
	
	public java.lang.String getMenuUrl() {
		return getStr("menu_url");
	}

	public M setSid(java.lang.Long sid) {
		set("sid", sid);
		return (M)this;
	}
	
	public java.lang.Long getSid() {
		return getLong("sid");
	}

	public M setIstop(java.lang.String istop) {
		set("istop", istop);
		return (M)this;
	}
	
	public java.lang.String getIstop() {
		return getStr("istop");
	}

	public M setMenuIcon(java.lang.String menuIcon) {
		set("menu_icon", menuIcon);
		return (M)this;
	}
	
	public java.lang.String getMenuIcon() {
		return getStr("menu_icon");
	}

	public M setSstatus(java.lang.String sstatus) {
		set("sstatus", sstatus);
		return (M)this;
	}
	
	public java.lang.String getSstatus() {
		return getStr("sstatus");
	}

	public M setRelationNo(java.lang.String relationNo) {
		set("relation_no", relationNo);
		return (M)this;
	}
	
	public java.lang.String getRelationNo() {
		return getStr("relation_no");
	}

	public M setRemarks(java.lang.String remarks) {
		set("remarks", remarks);
		return (M)this;
	}
	
	public java.lang.String getRemarks() {
		return getStr("remarks");
	}

	public M setIsshortcut(java.lang.String isshortcut) {
		set("isshortcut", isshortcut);
		return (M)this;
	}
	
	public java.lang.String getIsshortcut() {
		return getStr("isshortcut");
	}

	public M setIconImgUrl(java.lang.String iconImgUrl) {
		set("iconImgUrl", iconImgUrl);
		return (M)this;
	}
	
	public java.lang.String getIconImgUrl() {
		return getStr("iconImgUrl");
	}

}
