package com.xiaosong.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTblCompanyPost<M extends BaseTblCompanyPost<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setPostCode(java.lang.String postCode) {
		set("postCode", postCode);
		return (M)this;
	}
	
	public java.lang.String getPostCode() {
		return getStr("postCode");
	}

	public M setPostName(java.lang.String postName) {
		set("postName", postName);
		return (M)this;
	}
	
	public java.lang.String getPostName() {
		return getStr("postName");
	}

}
