package com.xiaosong.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTblRoomApplyRecord<M extends BaseTblRoomApplyRecord<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setRoomId(java.lang.Long roomId) {
		set("room_id", roomId);
		return (M)this;
	}
	
	public java.lang.Long getRoomId() {
		return getLong("room_id");
	}

	public M setApplyUserid(java.lang.Long applyUserid) {
		set("apply_userid", applyUserid);
		return (M)this;
	}
	
	public java.lang.Long getApplyUserid() {
		return getLong("apply_userid");
	}

	public M setApplyDate(java.lang.String applyDate) {
		set("apply_date", applyDate);
		return (M)this;
	}
	
	public java.lang.String getApplyDate() {
		return getStr("apply_date");
	}

	public M setApplyStartTime(java.math.BigDecimal applyStartTime) {
		set("apply_start_time", applyStartTime);
		return (M)this;
	}
	
	public java.math.BigDecimal getApplyStartTime() {
		return get("apply_start_time");
	}

	public M setApplyEndTime(java.math.BigDecimal applyEndTime) {
		set("apply_end_time", applyEndTime);
		return (M)this;
	}
	
	public java.math.BigDecimal getApplyEndTime() {
		return get("apply_end_time");
	}

	public M setTimeInterval(java.lang.String timeInterval) {
		set("time_interval", timeInterval);
		return (M)this;
	}
	
	public java.lang.String getTimeInterval() {
		return getStr("time_interval");
	}

	public M setRecordStatus(java.lang.Integer recordStatus) {
		set("record_status", recordStatus);
		return (M)this;
	}
	
	public java.lang.Integer getRecordStatus() {
		return getInt("record_status");
	}

	public M setPrice(java.math.BigDecimal price) {
		set("price", price);
		return (M)this;
	}
	
	public java.math.BigDecimal getPrice() {
		return get("price");
	}

	public M setCreateTime(java.lang.String createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	public java.lang.String getCreateTime() {
		return getStr("create_time");
	}

	public M setCancleTime(java.lang.String cancleTime) {
		set("cancle_time", cancleTime);
		return (M)this;
	}
	
	public java.lang.String getCancleTime() {
		return getStr("cancle_time");
	}

	public M setExt1(java.lang.String ext1) {
		set("ext1", ext1);
		return (M)this;
	}
	
	public java.lang.String getExt1() {
		return getStr("ext1");
	}

	public M setExt2(java.lang.String ext2) {
		set("ext2", ext2);
		return (M)this;
	}
	
	public java.lang.String getExt2() {
		return getStr("ext2");
	}

	public M setExt3(java.lang.String ext3) {
		set("ext3", ext3);
		return (M)this;
	}
	
	public java.lang.String getExt3() {
		return getStr("ext3");
	}

}
