package com.xiaosong.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTblVisitorRecord<M extends BaseTblVisitorRecord<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setVisitDate(java.lang.String visitDate) {
		set("visitDate", visitDate);
		return (M)this;
	}
	
	public java.lang.String getVisitDate() {
		return getStr("visitDate");
	}

	public M setVisitTime(java.lang.String visitTime) {
		set("visitTime", visitTime);
		return (M)this;
	}
	
	public java.lang.String getVisitTime() {
		return getStr("visitTime");
	}

	public M setUserId(java.lang.Long userId) {
		set("userId", userId);
		return (M)this;
	}
	
	public java.lang.Long getUserId() {
		return getLong("userId");
	}

	public M setVisitorId(java.lang.Long visitorId) {
		set("visitorId", visitorId);
		return (M)this;
	}
	
	public java.lang.Long getVisitorId() {
		return getLong("visitorId");
	}

	public M setReason(java.lang.String reason) {
		set("reason", reason);
		return (M)this;
	}
	
	public java.lang.String getReason() {
		return getStr("reason");
	}

	public M setCstatus(java.lang.String cstatus) {
		set("cstatus", cstatus);
		return (M)this;
	}
	
	public java.lang.String getCstatus() {
		return getStr("cstatus");
	}

	public M setDateType(java.lang.String dateType) {
		set("dateType", dateType);
		return (M)this;
	}
	
	public java.lang.String getDateType() {
		return getStr("dateType");
	}

	public M setStartDate(java.lang.String startDate) {
		set("startDate", startDate);
		return (M)this;
	}
	
	public java.lang.String getStartDate() {
		return getStr("startDate");
	}

	public M setEndDate(java.lang.String endDate) {
		set("endDate", endDate);
		return (M)this;
	}
	
	public java.lang.String getEndDate() {
		return getStr("endDate");
	}

	public M setAnswerContent(java.lang.String answerContent) {
		set("answerContent", answerContent);
		return (M)this;
	}
	
	public java.lang.String getAnswerContent() {
		return getStr("answerContent");
	}

	public M setOrgCode(java.lang.String orgCode) {
		set("orgCode", orgCode);
		return (M)this;
	}
	
	public java.lang.String getOrgCode() {
		return getStr("orgCode");
	}

	public M setCompanyId(java.lang.Long companyId) {
		set("companyId", companyId);
		return (M)this;
	}
	
	public java.lang.Long getCompanyId() {
		return getLong("companyId");
	}

	public M setRecordType(java.lang.Integer recordType) {
		set("recordType", recordType);
		return (M)this;
	}
	
	public java.lang.Integer getRecordType() {
		return getInt("recordType");
	}

	public M setReplyDate(java.lang.String replyDate) {
		set("replyDate", replyDate);
		return (M)this;
	}
	
	public java.lang.String getReplyDate() {
		return getStr("replyDate");
	}

	public M setReplyTime(java.lang.String replyTime) {
		set("replyTime", replyTime);
		return (M)this;
	}
	
	public java.lang.String getReplyTime() {
		return getStr("replyTime");
	}

	public M setVitype(java.lang.String vitype) {
		set("vitype", vitype);
		return (M)this;
	}
	
	public java.lang.String getVitype() {
		return getStr("vitype");
	}

	public M setReplyUserId(java.lang.Long replyUserId) {
		set("replyUserId", replyUserId);
		return (M)this;
	}
	
	public java.lang.Long getReplyUserId() {
		return getLong("replyUserId");
	}

	public M setIsReceive(java.lang.String isReceive) {
		set("isReceive", isReceive);
		return (M)this;
	}
	
	public java.lang.String getIsReceive() {
		return getStr("isReceive");
	}

}
