package com.xiaosong.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTblUserFriend<M extends BaseTblUserFriend<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setUserId(java.lang.Long userId) {
		set("userId", userId);
		return (M)this;
	}
	
	public java.lang.Long getUserId() {
		return getLong("userId");
	}

	public M setFriendId(java.lang.Long friendId) {
		set("friendId", friendId);
		return (M)this;
	}
	
	public java.lang.Long getFriendId() {
		return getLong("friendId");
	}

	public M setApplyType(java.lang.Long applyType) {
		set("applyType", applyType);
		return (M)this;
	}
	
	public java.lang.Long getApplyType() {
		return getLong("applyType");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

}
