package com.xiaosong.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTOper<M extends BaseTOper<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setOperCode(java.lang.String operCode) {
		set("oper_code", operCode);
		return (M)this;
	}
	
	public java.lang.String getOperCode() {
		return getStr("oper_code");
	}

	public M setOperName(java.lang.String operName) {
		set("oper_name", operName);
		return (M)this;
	}
	
	public java.lang.String getOperName() {
		return getStr("oper_name");
	}

	public M setOrgId(java.lang.Long orgId) {
		set("org_id", orgId);
		return (M)this;
	}
	
	public java.lang.Long getOrgId() {
		return getLong("org_id");
	}

	public M setRoleId(java.lang.Long roleId) {
		set("role_id", roleId);
		return (M)this;
	}
	
	public java.lang.Long getRoleId() {
		return getLong("role_id");
	}

	public M setOrgRelationNo(java.lang.String orgRelationNo) {
		set("org_relation_no", orgRelationNo);
		return (M)this;
	}
	
	public java.lang.String getOrgRelationNo() {
		return getStr("org_relation_no");
	}

	public M setPwd(java.lang.String pwd) {
		set("pwd", pwd);
		return (M)this;
	}
	
	public java.lang.String getPwd() {
		return getStr("pwd");
	}

	public M setSstatus(java.lang.String sstatus) {
		set("sstatus", sstatus);
		return (M)this;
	}
	
	public java.lang.String getSstatus() {
		return getStr("sstatus");
	}

	public M setLoginName(java.lang.String loginName) {
		set("login_name", loginName);
		return (M)this;
	}
	
	public java.lang.String getLoginName() {
		return getStr("login_name");
	}

}
