package com.xiaosong.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTRole<M extends BaseTRole<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setRoleName(java.lang.String roleName) {
		set("role_name", roleName);
		return (M)this;
	}
	
	public java.lang.String getRoleName() {
		return getStr("role_name");
	}

	public M setSid(java.lang.Long sid) {
		set("sid", sid);
		return (M)this;
	}
	
	public java.lang.Long getSid() {
		return getLong("sid");
	}

	public M setRoleRelationNo(java.lang.String roleRelationNo) {
		set("role_relation_no", roleRelationNo);
		return (M)this;
	}
	
	public java.lang.String getRoleRelationNo() {
		return getStr("role_relation_no");
	}

}
