package com.xiaosong.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTVisitAccessRecord<M extends BaseTVisitAccessRecord<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setPospCode(java.lang.String pospCode) {
		set("pospCode", pospCode);
		return (M)this;
	}
	
	public java.lang.String getPospCode() {
		return getStr("pospCode");
	}

	public M setOrgCode(java.lang.String orgCode) {
		set("orgCode", orgCode);
		return (M)this;
	}
	
	public java.lang.String getOrgCode() {
		return getStr("orgCode");
	}

	public M setVisitId(java.lang.Long visitId) {
		set("visitId", visitId);
		return (M)this;
	}
	
	public java.lang.Long getVisitId() {
		return getLong("visitId");
	}

	public M setInOrOut(java.lang.String inOrOut) {
		set("inOrOut", inOrOut);
		return (M)this;
	}
	
	public java.lang.String getInOrOut() {
		return getStr("inOrOut");
	}

	public M setVisitDate(java.lang.String visitDate) {
		set("visitDate", visitDate);
		return (M)this;
	}
	
	public java.lang.String getVisitDate() {
		return getStr("visitDate");
	}

	public M setVisitTime(java.lang.String visitTime) {
		set("visitTime", visitTime);
		return (M)this;
	}
	
	public java.lang.String getVisitTime() {
		return getStr("visitTime");
	}

	public M setTermNo(java.lang.String termNo) {
		set("termNo", termNo);
		return (M)this;
	}
	
	public java.lang.String getTermNo() {
		return getStr("termNo");
	}

	public M setHoldTermNo(java.lang.String holdTermNo) {
		set("holdTermNo", holdTermNo);
		return (M)this;
	}
	
	public java.lang.String getHoldTermNo() {
		return getStr("holdTermNo");
	}

	public M setOperator(java.lang.String operator) {
		set("operator", operator);
		return (M)this;
	}
	
	public java.lang.String getOperator() {
		return getStr("operator");
	}

}
