package com.xiaosong.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTDictItem<M extends BaseTDictItem<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setDictCode(java.lang.String dictCode) {
		set("dict_code", dictCode);
		return (M)this;
	}
	
	public java.lang.String getDictCode() {
		return getStr("dict_code");
	}

	public M setItemCode(java.lang.String itemCode) {
		set("item_code", itemCode);
		return (M)this;
	}
	
	public java.lang.String getItemCode() {
		return getStr("item_code");
	}

	public M setItemText(java.lang.String itemText) {
		set("item_text", itemText);
		return (M)this;
	}
	
	public java.lang.String getItemText() {
		return getStr("item_text");
	}

}
