package com.xiaosong.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTblButton<M extends BaseTblButton<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setBtnName(java.lang.String btnName) {
		set("btnName", btnName);
		return (M)this;
	}
	
	public java.lang.String getBtnName() {
		return getStr("btnName");
	}

	public M setBtnCode(java.lang.String btnCode) {
		set("btnCode", btnCode);
		return (M)this;
	}
	
	public java.lang.String getBtnCode() {
		return getStr("btnCode");
	}

	public M setActionUrl(java.lang.String actionUrl) {
		set("actionUrl", actionUrl);
		return (M)this;
	}
	
	public java.lang.String getActionUrl() {
		return getStr("actionUrl");
	}

	public M setMenuId(java.lang.Long menuId) {
		set("menuId", menuId);
		return (M)this;
	}
	
	public java.lang.Long getMenuId() {
		return getLong("menuId");
	}

}
