package com.xiaosong.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTblShareRoom<M extends BaseTblShareRoom<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setRoomName(java.lang.String roomName) {
		set("room_name", roomName);
		return (M)this;
	}
	
	public java.lang.String getRoomName() {
		return getStr("room_name");
	}

	public M setRoomAddr(java.lang.String roomAddr) {
		set("room_addr", roomAddr);
		return (M)this;
	}
	
	public java.lang.String getRoomAddr() {
		return getStr("room_addr");
	}

	public M setRoomType(java.lang.Integer roomType) {
		set("room_type", roomType);
		return (M)this;
	}
	
	public java.lang.Integer getRoomType() {
		return getInt("room_type");
	}

	public M setRoomShortContent(java.lang.String roomShortContent) {
		set("room_short_content", roomShortContent);
		return (M)this;
	}
	
	public java.lang.String getRoomShortContent() {
		return getStr("room_short_content");
	}

	public M setRoomImage(java.lang.String roomImage) {
		set("room_image", roomImage);
		return (M)this;
	}
	
	public java.lang.String getRoomImage() {
		return getStr("room_image");
	}

	public M setRoomOpenTime(java.lang.String roomOpenTime) {
		set("room_open_time", roomOpenTime);
		return (M)this;
	}
	
	public java.lang.String getRoomOpenTime() {
		return getStr("room_open_time");
	}

	public M setRoomCloseTime(java.lang.String roomCloseTime) {
		set("room_close_time", roomCloseTime);
		return (M)this;
	}
	
	public java.lang.String getRoomCloseTime() {
		return getStr("room_close_time");
	}

	public M setRoomPrice(java.lang.Integer roomPrice) {
		set("room_price", roomPrice);
		return (M)this;
	}
	
	public java.lang.Integer getRoomPrice() {
		return getInt("room_price");
	}

	public M setRoomManager(java.lang.Long roomManager) {
		set("room_manager", roomManager);
		return (M)this;
	}
	
	public java.lang.Long getRoomManager() {
		return getLong("room_manager");
	}

	public M setRoomStatus(java.lang.Integer roomStatus) {
		set("room_status", roomStatus);
		return (M)this;
	}
	
	public java.lang.Integer getRoomStatus() {
		return getInt("room_status");
	}

	public M setRoomOrgcode(java.lang.String roomOrgcode) {
		set("room_orgcode", roomOrgcode);
		return (M)this;
	}
	
	public java.lang.String getRoomOrgcode() {
		return getStr("room_orgcode");
	}

	public M setRoomCancleHour(java.lang.Integer roomCancleHour) {
		set("room_cancle_hour", roomCancleHour);
		return (M)this;
	}
	
	public java.lang.Integer getRoomCancleHour() {
		return getInt("room_cancle_hour");
	}

	public M setRoomPercent(java.lang.Integer roomPercent) {
		set("room_percent", roomPercent);
		return (M)this;
	}
	
	public java.lang.Integer getRoomPercent() {
		return getInt("room_percent");
	}

	public M setExt1(java.lang.String ext1) {
		set("ext1", ext1);
		return (M)this;
	}
	
	public java.lang.String getExt1() {
		return getStr("ext1");
	}

	public M setExt2(java.lang.String ext2) {
		set("ext2", ext2);
		return (M)this;
	}
	
	public java.lang.String getExt2() {
		return getStr("ext2");
	}

	public M setExt3(java.lang.String ext3) {
		set("ext3", ext3);
		return (M)this;
	}
	
	public java.lang.String getExt3() {
		return getStr("ext3");
	}

}
