package com.xiaosong.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTblCompany<M extends BaseTblCompany<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setCompanyCode(java.lang.String companyCode) {
		set("companyCode", companyCode);
		return (M)this;
	}
	
	public java.lang.String getCompanyCode() {
		return getStr("companyCode");
	}

	public M setCompanyName(java.lang.String companyName) {
		set("companyName", companyName);
		return (M)this;
	}
	
	public java.lang.String getCompanyName() {
		return getStr("companyName");
	}

	public M setCreateDate(java.lang.String createDate) {
		set("createDate", createDate);
		return (M)this;
	}
	
	public java.lang.String getCreateDate() {
		return getStr("createDate");
	}

	public M setCreateTime(java.lang.String createTime) {
		set("createTime", createTime);
		return (M)this;
	}
	
	public java.lang.String getCreateTime() {
		return getStr("createTime");
	}

	public M setPhone(java.lang.String phone) {
		set("phone", phone);
		return (M)this;
	}
	
	public java.lang.String getPhone() {
		return getStr("phone");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setApplyType(java.lang.String applyType) {
		set("applyType", applyType);
		return (M)this;
	}
	
	public java.lang.String getApplyType() {
		return getStr("applyType");
	}

	public M setCorporationID(java.lang.String corporationID) {
		set("corporationID", corporationID);
		return (M)this;
	}
	
	public java.lang.String getCorporationID() {
		return getStr("corporationID");
	}

	public M setLicenceNo(java.lang.String licenceNo) {
		set("licenceNo", licenceNo);
		return (M)this;
	}
	
	public java.lang.String getLicenceNo() {
		return getStr("licenceNo");
	}

	public M setAddr(java.lang.String addr) {
		set("addr", addr);
		return (M)this;
	}
	
	public java.lang.String getAddr() {
		return getStr("addr");
	}

	public M setOrgId(java.lang.Long orgId) {
		set("orgId", orgId);
		return (M)this;
	}
	
	public java.lang.Long getOrgId() {
		return getLong("orgId");
	}

	public M setCompanyFloor(java.lang.String companyFloor) {
		set("companyFloor", companyFloor);
		return (M)this;
	}
	
	public java.lang.String getCompanyFloor() {
		return getStr("companyFloor");
	}

	public M setIsyaoyue(java.lang.String isyaoyue) {
		set("isyaoyue", isyaoyue);
		return (M)this;
	}
	
	public java.lang.String getIsyaoyue() {
		return getStr("isyaoyue");
	}

}
