package com.xiaosong.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTblAppVersion<M extends BaseTblAppVersion<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setAppType(java.lang.String appType) {
		set("appType", appType);
		return (M)this;
	}
	
	public java.lang.String getAppType() {
		return getStr("appType");
	}

	public M setChannel(java.lang.String channel) {
		set("channel", channel);
		return (M)this;
	}
	
	public java.lang.String getChannel() {
		return getStr("channel");
	}

	public M setVersionName(java.lang.String versionName) {
		set("versionName", versionName);
		return (M)this;
	}
	
	public java.lang.String getVersionName() {
		return getStr("versionName");
	}

	public M setVersionNum(java.lang.String versionNum) {
		set("versionNum", versionNum);
		return (M)this;
	}
	
	public java.lang.String getVersionNum() {
		return getStr("versionNum");
	}

	public M setIsImmediatelyUpdate(java.lang.String isImmediatelyUpdate) {
		set("isImmediatelyUpdate", isImmediatelyUpdate);
		return (M)this;
	}
	
	public java.lang.String getIsImmediatelyUpdate() {
		return getStr("isImmediatelyUpdate");
	}

	public M setUpdateUrl(java.lang.String updateUrl) {
		set("updateUrl", updateUrl);
		return (M)this;
	}
	
	public java.lang.String getUpdateUrl() {
		return getStr("updateUrl");
	}

	public M setMemo(java.lang.String memo) {
		set("memo", memo);
		return (M)this;
	}
	
	public java.lang.String getMemo() {
		return getStr("memo");
	}

	public M setCreateDate(java.lang.String createDate) {
		set("createDate", createDate);
		return (M)this;
	}
	
	public java.lang.String getCreateDate() {
		return getStr("createDate");
	}

}
