package com.xiaosong.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTblNews<M extends BaseTblNews<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setNewsDate(java.lang.String newsDate) {
		set("newsDate", newsDate);
		return (M)this;
	}
	
	public java.lang.String getNewsDate() {
		return getStr("newsDate");
	}

	public M setNewsName(java.lang.String newsName) {
		set("newsName", newsName);
		return (M)this;
	}
	
	public java.lang.String getNewsName() {
		return getStr("newsName");
	}

	public M setNewsDetail(java.lang.String newsDetail) {
		set("newsDetail", newsDetail);
		return (M)this;
	}
	
	public java.lang.String getNewsDetail() {
		return getStr("newsDetail");
	}

	public M setNewsImageUrl(java.lang.String newsImageUrl) {
		set("newsImageUrl", newsImageUrl);
		return (M)this;
	}
	
	public java.lang.String getNewsImageUrl() {
		return getStr("newsImageUrl");
	}

	public M setNewsUrl(java.lang.String newsUrl) {
		set("newsUrl", newsUrl);
		return (M)this;
	}
	
	public java.lang.String getNewsUrl() {
		return getStr("newsUrl");
	}

	public M setNewsStatus(java.lang.String newsStatus) {
		set("newsStatus", newsStatus);
		return (M)this;
	}
	
	public java.lang.String getNewsStatus() {
		return getStr("newsStatus");
	}

}
