package com.xiaosong.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTblUserAccount<M extends BaseTblUserAccount<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setUserId(java.lang.Long userId) {
		set("userId", userId);
		return (M)this;
	}
	
	public java.lang.Long getUserId() {
		return getLong("userId");
	}

	public M setSysPwd(java.lang.String sysPwd) {
		set("sysPwd", sysPwd);
		return (M)this;
	}
	
	public java.lang.String getSysPwd() {
		return getStr("sysPwd");
	}

	public M setPayPwd(java.lang.String payPwd) {
		set("payPwd", payPwd);
		return (M)this;
	}
	
	public java.lang.String getPayPwd() {
		return getStr("payPwd");
	}

	public M setCstatus(java.lang.String cstatus) {
		set("cstatus", cstatus);
		return (M)this;
	}
	
	public java.lang.String getCstatus() {
		return getStr("cstatus");
	}

	public M setGesturePwd(java.lang.String gesturePwd) {
		set("gesturePwd", gesturePwd);
		return (M)this;
	}
	
	public java.lang.String getGesturePwd() {
		return getStr("gesturePwd");
	}

	public M setHandleCause(java.lang.String handleCause) {
		set("handleCause", handleCause);
		return (M)this;
	}
	
	public java.lang.String getHandleCause() {
		return getStr("handleCause");
	}

	public M setHandleTime(java.lang.String handleTime) {
		set("handleTime", handleTime);
		return (M)this;
	}
	
	public java.lang.String getHandleTime() {
		return getStr("handleTime");
	}

	public M setOperId(java.lang.Long operId) {
		set("operId", operId);
		return (M)this;
	}
	
	public java.lang.Long getOperId() {
		return getLong("operId");
	}

}
